// Example User Response Structure
export const Auth_RESPONSE_STRUCTURE = 
  {
    "Sno": "14",
    "New_Card_no": "28352",
    "Emp_Name ": "Harish",
    "User_Approval_Name": "admin",
    "signature": "picture file for sign",
    "Email_Address": "Harish@atoz.co.tz",
    "Company_Id": "28",
    "STATUS_ENTRY": "CF",
    "ORDER_NO": "STR-2",
    "Password_User": "admin@123",
    "Online_Access": "AC",
    "PO_Approval_YN": "YES",
    "Cash_Advance_Approval_YN": "YES",
    "Credit_Limit_Approval_YN": "YES",
    "Price_Approval_YN": "YES",
    "Goods_Request_Approval_YN": "YES",
    "Inter_company_Approval_YN": "YES",
    "Sales_Return_Approval_YN": "YES",
    "Gate_Pass_Approval_YN": "YES",
    "Product_Creation_Approval_YN": "YES",
    "Customer_Creation_Approval_YN": "YES",
    "Wastage_Delivery_Approval_YN": "YES",
    "Work_Order_Approval_YN": "YES",
    "PFL_Work_Order_Approval_YN": "YES",
    "PPRB_Roll_Cutt_Templates_YN": "YES",
    "Expat_Travel_Leave_Approval_YN": "YES",
    "Employee_Signed_As": "Director Signature",
    "SALES_PI_APPROVAL_YN": "YES",
    "PURCHASE_PI_APPROVAL_YN": "YES",
    "OTP": "",
    "Apparels_Dashboard_YN": "YES",
    "PO_Approval_Head_YN": "YES",
    "OverTime_Approval_YN": "YES",
    "Expat_Leave_Encashment_YN": "YES",
    "BoncePurchaseOrder_Approval_YN": "YES",
    "BondReleaseRequest_Approval_YN": "YES"
  }
